#pragma config(Motor,  port2,           frontRightMotor, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           backRightMotor, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           frontLeftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           backLeftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           captureMotor,  tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           flipMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

short deadZone(short value, float deadzonePercent) {
	float range = 0.01 * deadzonePercent * 127;
	if (abs(value) < range)
  {
    return 0;
  }
  else
  {
    return value;
  }

}

task main()
{
	int captureMotor = motor[port6];
	int flipMotor = motor[port7];

	while(true){
		short rightValue = deadZone(vexRT[Ch2], 8);
		short leftValue = deadZone(vexRT[Ch3], 8);
		motor[frontRightMotor] = rightValue;
		motor[backRightMotor] = rightValue;

		motor[frontLeftMotor] = leftValue;
		motor[backLeftMotor] = leftValue;

		if (vexRT[Btn6D] && !vexRT[Btn6U]){
			captureMotor = 127;
		}else if(vexRT[Btn6U] && !vexRT[Btn6D]){
			captureMotor = -127;
		}else{
			captureMotor = 0;
		}

		if (vexRT[Btn5D] && !vexRT[Btn5U]){
			flipMotor = 127;
		}else if(vexRT[Btn5U] && !vexRT[Btn5D]){
			flipMotor = -127;
		}else{
			flipMotor = 0;
		}
	}
}
